import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { useLibrary } from '../library/useLibrary';
import { AppShell } from '../../ui/AppShell';
import { Button, Eyebrow, Pill, Progress, SectionHeader } from '../../ui/primitives';
import { color, font, radius, space, type } from '../../ui/tokens';
export default function ProfileScreen() { const library = useLibrary(); const done = library.items.filter((item) => item.status === 'done').length; const reading = library.items.filter((item) => item.status === 'reading').length;
 return <AppShell active="today" title="Profile"><ScrollView contentContainerStyle={styles.content}><View style={styles.profile}><View style={styles.portrait}><Text style={styles.portraitText}>M</Text></View><Text style={styles.name}>pluto.reader</Text><Text style={styles.blurb}>Comic explorer, mood reader, forever collector.</Text><Button kind="secondary" onPress={() => router.push('/settings')}>Edit profile</Button></View><View style={styles.stats}>{[['Titles', library.items.length], ['Finished', done], ['Reading', reading], ['Check-ins', done]].map(([label, count]) => <View key={label as string} style={styles.stat}><Text style={styles.statNumber}>{count}</Text><Text style={styles.statLabel}>{label}</Text></View>)}</View><View style={styles.persona}><Eyebrow>Your reading persona</Eyebrow><Text style={styles.personaTitle}>The Explorer</Text><Text style={styles.personaCopy}>You enjoy darker, character-driven stories but keep making room for a new world.</Text></View><SectionHeader title="Taste profile" action="See all" /><View style={styles.taste}>{[['Mystery', .82], ['Character-driven', .74], ['Sci-fi', .61], ['Big commitment', .32]].map(([label, value]) => <View key={label as string} style={styles.tasteRow}><Text style={styles.tasteLabel}>{label}</Text><View style={{ flex: 1 }}><Progress value={value as number} /></View></View>)}</View><SectionHeader title="Reading habits" /><View style={styles.habits}><Text style={styles.habitsNumber}>12</Text><Text style={styles.habitsCopy}>reading days this month{`\n`}Small steps. A better library.</Text></View><SectionHeader title="Your journal" action="View history" /><View style={styles.journal}><Text style={styles.journalDate}>Recently</Text><Text style={styles.journalTitle}>Your reading history will appear here.</Text><Text style={styles.journalCopy}>Check-ins turn moments with comics into a personal record.</Text></View></ScrollView></AppShell>; }
const styles = StyleSheet.create({ content: { padding: space.lg, paddingBottom: 105 }, profile: { alignItems: 'center', gap: 8 }, portrait: { width: 92, height: 92, borderRadius: 46, backgroundColor: color.accentDeep, borderWidth: 3, borderColor: color.accent, alignItems: 'center', justifyContent: 'center' }, portraitText: { color: color.text, fontFamily: font.display, fontSize: 42 }, name: { color: color.text, fontFamily: font.display, fontSize: 26, marginTop: 3 }, blurb: { color: color.muted, fontFamily: font.body, fontSize: type.caption, textAlign: 'center', marginBottom: 4 }, stats: { flexDirection: 'row', marginTop: 24, backgroundColor: color.surface, borderRadius: radius.md, borderWidth: 1, borderColor: color.border }, stat: { flex: 1, alignItems: 'center', paddingVertical: 14 }, statNumber: { color: color.text, fontFamily: font.display, fontSize: 21 }, statLabel: { color: color.faint, fontFamily: font.bodyMedium, fontSize: 10, marginTop: 3 }, persona: { backgroundColor: color.surface, borderColor: color.border, borderWidth: 1, borderRadius: radius.lg, padding: 18, marginTop: 18 }, personaTitle: { color: color.accent, fontFamily: font.display, fontSize: type.title, marginTop: 7 }, personaCopy: { color: color.muted, fontFamily: font.body, fontSize: type.caption, lineHeight: 18, marginTop: 5 }, taste: { gap: 13 }, tasteRow: { flexDirection: 'row', gap: 12, alignItems: 'center' }, tasteLabel: { width: 132, color: color.text, fontFamily: font.bodyMedium, fontSize: type.caption }, habits: { flexDirection: 'row', alignItems: 'center', gap: 16, backgroundColor: color.surface2, borderRadius: radius.md, padding: 16, borderWidth: 1, borderColor: color.border }, habitsNumber: { color: color.accent, fontFamily: font.display, fontSize: 40 }, habitsCopy: { color: color.muted, fontFamily: font.body, fontSize: type.caption, lineHeight: 18 }, journal: { borderLeftWidth: 2, borderLeftColor: color.accent, paddingLeft: 14, paddingVertical: 4 }, journalDate: { color: color.faint, fontFamily: font.bodyMedium, fontSize: 11 }, journalTitle: { color: color.text, fontFamily: font.displayMedium, fontSize: type.subtitle, marginTop: 5 }, journalCopy: { color: color.muted, fontFamily: font.body, fontSize: type.caption, lineHeight: 18, marginTop: 4 } });
