import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { useDiscover } from './useDiscover';
import { AppShell } from '../../ui/AppShell';
import { ComicCover } from '../../ui/comic';
import { Button, EmptyState, Pill, Sheet } from '../../ui/primitives';
import { color, font, radius, space, type } from '../../ui/tokens';

export default function DiscoverScreen() { const deck = useDiscover(); const [rating, setRating] = useState(false); const card = deck.current;
  return <AppShell active="discover" title="Discover"><View style={styles.page}><View style={styles.filters}>{['For you', 'Hidden gems', 'New to you', 'Short reads'].map((filter, index) => <Pill key={filter} label={filter} active={index === 0} />)}</View>{card ? <><View style={styles.deck}><View style={styles.ghost} /><View style={styles.card}><ComicCover title={card.work.title} size="hero" /><View style={styles.info}><Text style={styles.title}>{card.work.title}</Text><Text style={styles.meta}>{card.work.genres.slice(0, 2).join(' · ') || 'A story worth considering'}</Text><Text style={styles.copy}>{card.kind === 'near' ? 'Close to what you already love.' : card.kind === 'probe' ? 'A thoughtful change of pace.' : 'A little outside your usual shelf.'}</Text></View></View></View><View style={styles.controls}><Pressable onPress={deck.pass} style={styles.pass}><Text style={styles.passIcon}>×</Text><Text style={styles.controlText}>Pass</Text></Pressable><Pressable onPress={() => setRating(true)} style={styles.rate}><Text style={styles.rateIcon}>↑</Text><Text style={styles.controlText}>Rate</Text></Pressable><Pressable onPress={deck.read} style={styles.read}><Text style={styles.readIcon}>♥</Text><Text style={styles.controlText}>Read</Text></Pressable></View><Text style={styles.help}>Swipe left to pass, right to save, up to quick rate.</Text></> : <EmptyState mark="✦" title="That’s enough for now." copy="A small deck makes room for better decisions." action="Start again" onAction={deck.reset} />}{rating ? <View style={styles.overlay}><Sheet title="Quick rate"><Text style={styles.rateCopy}>A small signal goes a long way.</Text><View style={styles.rateButtons}><Button kind="secondary" onPress={() => { deck.rate(1); setRating(false); }}>Meh</Button><Button kind="secondary" onPress={() => { deck.rate(2); setRating(false); }}>Good</Button><Button onPress={() => { deck.rate(3); setRating(false); }}>Loved</Button></View></Sheet></View> : null}</View></AppShell>; }
const styles = StyleSheet.create({ page: { flex: 1, padding: space.lg, paddingBottom: 22 }, filters: { flexDirection: 'row', gap: 8, flexWrap: 'wrap' }, deck: { flex: 1, minHeight: 370, justifyContent: 'center', alignItems: 'center', marginTop: 8 }, ghost: { position: 'absolute', width: '82%', height: 350, borderRadius: radius.lg, backgroundColor: color.surface2, transform: [{ rotate: '4deg' }], top: 37 }, card: { width: '88%', backgroundColor: color.surface, borderColor: color.border, borderWidth: 1, borderRadius: radius.lg, padding: 16, flexDirection: 'row', gap: 14, shadowColor: '#000', shadowOpacity: 0.6, shadowRadius: 18, elevation: 9 }, info: { flex: 1, justifyContent: 'center' }, title: { color: color.text, fontFamily: font.display, fontSize: 25, lineHeight: 29 }, meta: { color: color.accent, fontFamily: font.bodyMedium, fontSize: 12, marginTop: 7, textTransform: 'capitalize' }, copy: { color: color.muted, fontFamily: font.body, fontSize: 12, lineHeight: 18, marginTop: 12 }, controls: { flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 28 }, pass: { alignItems: 'center', gap: 4 }, rate: { alignItems: 'center', gap: 4 }, read: { alignItems: 'center', gap: 4 }, passIcon: { color: color.muted, fontSize: 33, width: 57, height: 57, textAlign: 'center', textAlignVertical: 'center', borderWidth: 1, borderColor: color.border, borderRadius: 29 }, rateIcon: { color: color.text, fontSize: 25, width: 42, height: 42, textAlign: 'center', textAlignVertical: 'center', borderRadius: 21, backgroundColor: color.surface2 }, readIcon: { color: color.text, fontSize: 24, width: 57, height: 57, textAlign: 'center', textAlignVertical: 'center', borderRadius: 29, backgroundColor: color.accent }, controlText: { color: color.muted, fontFamily: font.bodyMedium, fontSize: 11 }, help: { color: color.faint, fontFamily: font.body, fontSize: 12, textAlign: 'center', marginTop: 15 }, overlay: { ...StyleSheet.absoluteFill, zIndex: 2, justifyContent: 'flex-end', backgroundColor: '#000000aa', margin: -space.lg }, rateCopy: { color: color.muted, fontFamily: font.body, fontSize: type.body, marginBottom: 14 }, rateButtons: { gap: 8 } });
