import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { usePaths } from './usePaths';
import { AppShell } from '../../ui/AppShell';
import { ComicCover, ComicRow } from '../../ui/comic';
import { Button, EmptyState, Eyebrow, Pill, Progress, SectionHeader } from '../../ui/primitives';
import { color, font, radius, space, type } from '../../ui/tokens';

export default function PathsScreen() {
  const state = usePaths(); const selected = state.selected;
  if (selected) return <AppShell active="paths" title="Path detail"><ScrollView contentContainerStyle={styles.content}><Text onPress={() => state.select(null)} style={styles.back}>‹ All paths</Text><Eyebrow>Reading journey</Eyebrow><Text style={styles.detailTitle}>{selected.name}</Text><Text style={styles.detailCopy}>Follow the story in a clear order. Context expands only when you ask for it.</Text><View style={styles.levels}>{(['simple', 'recommended', 'completionist'] as const).map((level) => <Pill key={level} label={level} active={state.level === level} onPress={() => state.setLevel(level)} />)}</View><View style={styles.progressLine}><Text style={styles.progressLabel}>{selected.done} of {selected.items.length} completed</Text><Progress value={selected.items.length ? selected.done / selected.items.length : 0} /></View><View style={styles.timeline}>{selected.items.map((item, index) => <View key={item.workId} style={styles.timelineItem}><View style={[styles.node, item.status === 'done' && styles.nodeDone]}><Text style={styles.nodeText}>{item.status === 'done' ? '✓' : index + 1}</Text></View><View style={styles.line} /><ComicCover title={item.title} size="tiny" /><View style={{ flex: 1 }}><Text style={styles.itemTitle}>{item.title}</Text><Text style={styles.itemMeta}>{item.workId === selected.nextId ? 'You are here' : item.status === 'done' ? 'Completed' : 'Next in journey'}</Text></View></View>)}</View><SectionHeader title="Go deeper" /><View style={styles.deep}><Text style={styles.deepTitle}>Rabbit hole</Text><Text style={styles.deepCopy}>Related stories, same universe, and creator paths—only as far as you want to go.</Text><Button kind="secondary">Explore related stories</Button></View></ScrollView></AppShell>;
  return <AppShell active="paths" title="Paths"><ScrollView contentContainerStyle={styles.content}><Text style={styles.intro}>What should you read before or after this?</Text><View style={styles.chips}>{['For you', 'Reading', 'Universe', 'Character', 'Events'].map((chip, index) => <Pill key={chip} label={chip} active={index === 0} />)}</View>{state.paths.length ? <>{state.paths.slice(0, 1).map((path) => <View key={path.id} style={styles.featured}><View style={{ flex: 1 }}><Eyebrow>Featured path</Eyebrow><Text style={styles.featuredTitle}>{path.name}</Text><Text style={styles.featuredCopy}>{path.items.length} works · a clear story journey</Text><Button onPress={() => state.select(path.id)} style={{ marginTop: 18 }}>{path.nextId ? 'Continue path  →' : 'View path  →'}</Button></View><ComicCover title={path.items[0]?.title ?? path.name} size="hero" /></View>)}<SectionHeader title="Your paths" />{state.paths.map((path) => <ComicRow key={path.id} title={path.name} meta={`${path.items.length} works · ${path.done} complete`} status={path.nextId ? 'Continue path' : 'Completed'} onPress={() => state.select(path.id)} />)}</> : <EmptyState title="No paths yet" copy="Once you add books, ComicPill will make the next step feel obvious." />}</ScrollView></AppShell>;
}
const styles = StyleSheet.create({ content: { padding: space.lg, paddingBottom: 105 }, intro: { color: color.text, fontFamily: font.display, fontSize: 27, lineHeight: 34, maxWidth: 310 }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginVertical: 18 }, featured: { flexDirection: 'row', gap: 12, padding: 14, borderRadius: radius.lg, backgroundColor: color.surface, borderWidth: 1, borderColor: color.border }, featuredTitle: { color: color.text, fontFamily: font.display, fontSize: type.title, marginTop: 5 }, featuredCopy: { color: color.muted, fontFamily: font.body, fontSize: type.caption, marginTop: 5 }, back: { color: color.muted, fontFamily: font.bodyMedium, fontSize: type.body, marginBottom: 18 }, detailTitle: { color: color.text, fontFamily: font.display, fontSize: 31, marginTop: 6 }, detailCopy: { color: color.muted, fontFamily: font.body, fontSize: type.body, lineHeight: 23, marginTop: 8 }, levels: { flexDirection: 'row', gap: 8, marginVertical: 18 }, progressLine: { gap: 8, marginBottom: 18 }, progressLabel: { color: color.muted, fontFamily: font.bodyMedium, fontSize: type.caption }, timeline: { gap: 0 }, timelineItem: { flexDirection: 'row', minHeight: 78, gap: 10, alignItems: 'center', position: 'relative' }, node: { width: 28, height: 28, borderRadius: 14, borderWidth: 1, borderColor: color.faint, backgroundColor: color.surface, alignItems: 'center', justifyContent: 'center', zIndex: 1 }, nodeDone: { backgroundColor: color.positive, borderColor: color.positive }, nodeText: { color: color.text, fontFamily: font.bodySemibold, fontSize: 11 }, line: { position: 'absolute', width: 1, backgroundColor: color.border, left: 14, top: 28, bottom: -12 }, itemTitle: { color: color.text, fontFamily: font.displayMedium, fontSize: type.subtitle }, itemMeta: { color: color.accent, fontFamily: font.bodyMedium, fontSize: 11, marginTop: 4, textTransform: 'capitalize' }, deep: { backgroundColor: color.surface2, borderRadius: radius.md, borderColor: color.border, borderWidth: 1, padding: 16, gap: 7 }, deepTitle: { color: color.text, fontFamily: font.displayMedium, fontSize: type.subtitle }, deepCopy: { color: color.muted, fontFamily: font.body, fontSize: type.caption, lineHeight: 18 } });
