import { StyleSheet, Text, View } from 'react-native';
import { FlashList } from '@shopify/flash-list';
import { usePaths } from './usePaths';
import { AppShell } from '../../ui/AppShell';
import { ComicCover, ComicRow } from '../../ui/comic';
import { Button, EmptyState, Eyebrow, Pill, Progress, SectionHeader } from '../../ui/primitives';
import { color, font, radius, space, type } from '../../ui/tokens';

type PathCard = ReturnType<typeof usePaths>['paths'][number];
export default function PathsScreen() {
  const state = usePaths(); const selected = state.selected;
  if (selected) return <AppShell active="paths" title="Path detail"><FlashList data={selected.items} keyExtractor={(item) => item.workId} getItemType={() => 'timeline-item'} renderItem={({ item, index }) => <TimelineItem item={item} index={index} nextId={selected.nextId} isLast={index === selected.items.length - 1} />} contentContainerStyle={styles.content} ListHeaderComponent={<PathDetailHeader name={selected.name} done={selected.done} total={selected.items.length} level={state.level} setLevel={state.setLevel} selectBack={() => state.select(null)} />} ListFooterComponent={<><SectionHeader title="Go deeper" /><View style={styles.deep}><Text style={styles.deepTitle}>Rabbit hole</Text><Text style={styles.deepCopy}>Related stories, same universe, and creator paths—only as far as you want to go.</Text><Button kind="secondary">Explore related stories</Button></View></>} /></AppShell>;
  const featured = state.paths[0];
  return <AppShell active="paths" title="Paths"><FlashList data={state.paths} keyExtractor={(item) => item.id} getItemType={() => 'path-row'} renderItem={({ item }) => <ComicRow title={item.name} recyclingKey={item.id} meta={`${item.items.length} works · ${item.done} complete`} status={item.nextId ? 'Continue path' : 'Completed'} onPress={() => state.select(item.id)} />} contentContainerStyle={styles.content} ListHeaderComponent={<><Text style={styles.intro}>What should you read before or after this?</Text><View style={styles.chips}>{['For you', 'Reading', 'Universe', 'Character', 'Events'].map((chip, index) => <Pill key={chip} label={chip} active={index === 0} />)}</View>{featured ? <View style={styles.featured}><View style={styles.featuredBody}><Eyebrow>Featured path</Eyebrow><Text numberOfLines={2} ellipsizeMode="tail" style={styles.featuredTitle}>{featured.name}</Text><Text style={styles.featuredCopy}>{featured.items.length} works · a clear story journey</Text><Button onPress={() => state.select(featured.id)} style={{ marginTop: 18 }}>{featured.nextId ? 'Continue path  →' : 'View path  →'}</Button></View><ComicCover title={featured.items[0]?.title ?? featured.name} workId={featured.items[0]?.workId} size="hero" recyclingKey={featured.id} /></View> : null}<SectionHeader title="Your paths" /></>} ListEmptyComponent={<EmptyState title="No paths yet" copy="Once you add books, ComicPill will make the next step feel obvious." />} /></AppShell>;
}

function PathDetailHeader({ name, done, total, level, setLevel, selectBack }: { name: string; done: number; total: number; level: ReturnType<typeof usePaths>['level']; setLevel: ReturnType<typeof usePaths>['setLevel']; selectBack: () => void }) {
  return <><Text onPress={selectBack} style={styles.back}>‹ All paths</Text><Eyebrow>Reading journey</Eyebrow><Text numberOfLines={2} ellipsizeMode="tail" style={styles.detailTitle}>{name}</Text><Text style={styles.detailCopy}>Follow the story in a clear order. Context expands only when you ask for it.</Text><View style={styles.levels}>{(['simple', 'recommended', 'completionist'] as const).map((item) => <Pill key={item} label={item} active={level === item} onPress={() => setLevel(item)} />)}</View><View style={styles.progressLine}><Text style={styles.progressLabel}>{done} of {total} completed</Text><Progress value={total ? done / total : 0} /></View></>;
}
function TimelineItem({ item, index, nextId, isLast }: { item: PathCard['items'][number]; index: number; nextId: string | null; isLast: boolean }) {
  return <View style={styles.timelineItem}><View style={[styles.node, item.status === 'done' && styles.nodeDone]}><Text style={styles.nodeText}>{item.status === 'done' ? '✓' : index + 1}</Text></View>{!isLast ? <View style={styles.line} /> : null}<ComicCover title={item.title} workId={item.workId} size="tiny" recyclingKey={item.workId} /><View style={styles.itemBody}><Text numberOfLines={1} ellipsizeMode="tail" style={styles.itemTitle}>{item.title}</Text><Text style={styles.itemMeta}>{item.workId === nextId ? 'You are here' : item.status === 'done' ? 'Completed' : 'Next in journey'}</Text></View></View>;
}
const styles = StyleSheet.create({ content: { padding: space.lg, paddingBottom: 105 }, intro: { color: color.text, fontFamily: font.display, fontSize: 27, lineHeight: 34, maxWidth: 310 }, chips: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginVertical: 18 }, featured: { flexDirection: 'row', gap: 12, padding: 14, borderRadius: radius.lg, backgroundColor: color.surface, borderWidth: 1, borderColor: color.border }, featuredBody: { flex: 1, minWidth: 0 }, featuredTitle: { color: color.text, fontFamily: font.display, fontSize: type.title, marginTop: 5 }, featuredCopy: { color: color.muted, fontFamily: font.body, fontSize: type.caption, marginTop: 5 }, back: { color: color.muted, fontFamily: font.bodyMedium, fontSize: type.body, marginBottom: 18 }, detailTitle: { color: color.text, fontFamily: font.display, fontSize: 31, marginTop: 6 }, detailCopy: { color: color.muted, fontFamily: font.body, fontSize: type.body, lineHeight: 23, marginTop: 8 }, levels: { flexDirection: 'row', gap: 8, marginVertical: 18 }, progressLine: { gap: 8, marginBottom: 18 }, progressLabel: { color: color.muted, fontFamily: font.bodyMedium, fontSize: type.caption }, timelineItem: { flexDirection: 'row', minHeight: 78, gap: 10, alignItems: 'center', position: 'relative' }, node: { width: 28, height: 28, borderRadius: 14, borderWidth: 1, borderColor: color.faint, backgroundColor: color.surface, alignItems: 'center', justifyContent: 'center', zIndex: 1 }, nodeDone: { backgroundColor: color.positive, borderColor: color.positive }, nodeText: { color: color.text, fontFamily: font.bodySemibold, fontSize: 11 }, line: { position: 'absolute', width: 1, backgroundColor: color.border, left: 14, top: 28, bottom: -12 }, itemBody: { flex: 1, minWidth: 0 }, itemTitle: { color: color.text, fontFamily: font.displayMedium, fontSize: type.subtitle }, itemMeta: { color: color.accent, fontFamily: font.bodyMedium, fontSize: 11, marginTop: 4, textTransform: 'capitalize' }, deep: { backgroundColor: color.surface2, borderRadius: radius.md, borderColor: color.border, borderWidth: 1, padding: 16, gap: 7 }, deepTitle: { color: color.text, fontFamily: font.displayMedium, fontSize: type.subtitle }, deepCopy: { color: color.muted, fontFamily: font.body, fontSize: type.caption, lineHeight: 18 } });
