import { Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Button, SectionHeader } from '../../ui/primitives';
import { space, type } from '../../ui/tokens';
import { useAppearance } from '../../ui/theme';
const groups = [
  ['Account', 'Notifications', 'Reading reminders', 'New release alerts'],
  ['Data & privacy', 'Personalized recommendations', 'Anonymous analytics', 'Export my data', 'Clear local data'],
  ['App', 'Appearance', 'Language', 'Currency', 'Accessibility'],
  ['Support', 'Help & feedback', 'About ComicPill'],
];
export default function SettingsScreen() { const { theme, typography } = useAppearance(); const c = theme.colors; return <ScrollView style={[styles.page, { backgroundColor: c.background }]} contentContainerStyle={styles.content}><Text onPress={() => router.back()} style={[styles.back, { color: c.textSecondary, fontFamily: typography.bodyMedium }]}>‹ Profile</Text><Text style={[styles.title, { color: c.textPrimary, fontFamily: typography.display }]}>Settings</Text><Text style={[styles.subtitle, { color: c.textSecondary, fontFamily: typography.body }]}>Quiet controls for the rest of your reading life.</Text>{groups.map(([heading, ...items]) => <View key={heading}><SectionHeader title={heading} />{items.map((item, index) => <Pressable key={item} disabled={item !== 'Help & feedback' && item !== 'Appearance'} onPress={() => item === 'Help & feedback' ? router.push('/feedback') : item === 'Appearance' ? router.push('/appearance') : undefined} style={[styles.row, { borderBottomColor: c.border }]}><View><Text style={[styles.rowText, { color: c.textPrimary, fontFamily: typography.body }]}>{item}</Text>{item === 'Appearance' ? <Text style={[styles.appearanceValue, { color: c.textSecondary, fontFamily: typography.body }]}> {theme.name} · {typography.name}</Text> : null}</View>{index < 2 && heading !== 'Support' && item !== 'Appearance' ? <View style={[styles.toggle, { backgroundColor: c.toggleActive }]}><View style={[styles.toggleDot, { backgroundColor: c.primaryForeground }]} /></View> : <Text style={[styles.chevron, { color: c.textSecondary }]}>›</Text>}</Pressable>)}</View>)}<Button kind="destructive" style={{ marginTop: 30 }}>Delete my account</Button></ScrollView>; }
const styles = StyleSheet.create({ page: { flex: 1 }, content: { padding: space.lg, paddingTop: 60, paddingBottom: 40 }, back: { marginBottom: 18 }, title: { fontSize: 34 }, subtitle: { fontSize: type.body, marginTop: 6 }, row: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 15, borderBottomWidth: StyleSheet.hairlineWidth }, rowText: { fontSize: type.body }, appearanceValue: { fontSize: type.caption, marginTop: 2 }, chevron: { fontSize: 24 }, toggle: { width: 42, height: 24, borderRadius: 12, padding: 3, alignItems: 'flex-end' }, toggleDot: { width: 18, height: 18, borderRadius: 9 } });
