import { ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Button, Eyebrow, SectionHeader } from '../../ui/primitives';
import { ComicCover } from '../../ui/comic';
import { color, font, radius, space, type } from '../../ui/tokens';
export function SourcesScreen() { return <ScrollView style={styles.page} contentContainerStyle={styles.content}><Text onPress={() => router.back()} style={styles.back}>‹ Back</Text><Text style={styles.title}>Sources & metadata</Text><Text style={styles.copy}>ComicPill shows its sources so you know where information comes from.</Text><View style={styles.work}><ComicCover title="The Long Halloween" size="list" /><View><Text style={styles.workTitle}>The Long Halloween</Text><Text style={styles.meta}>DC Comics · 1996</Text></View></View><SectionHeader title="This edition" /><Rows items={['Writer  Jeph Loeb', 'Artist  Tim Sale', 'Format  Single issues', 'Metadata source  Publisher data', 'Cover source  Official cover art']} /><SectionHeader title="How we make decisions" /><Text style={styles.copy}>Reading-order context comes from confirmed official and third-party sources. ComicPill’s verdicts are personal interpretations, not metadata facts.</Text></ScrollView>; }
export function NotificationsScreen() { const notes = [['Your next path title is ready', 'The next story in Gotham & Crime is waiting.'], ['Time for a quick check-in', 'Tell ComicPill what stayed with you.'], ['A comic on your list is available', 'Prices update when you’re back online.']]; return <ScrollView style={styles.page} contentContainerStyle={styles.content}><Text onPress={() => router.back()} style={styles.back}>‹ Back</Text><Text style={styles.title}>Notifications</Text><Text style={styles.copy}>Useful prompts, never noise.</Text>{notes.map(([title, copy]) => <View key={title} style={styles.note}><Text style={styles.noteMark}>✦</Text><View style={{ flex: 1 }}><Text style={styles.noteTitle}>{title}</Text><Text style={styles.noteCopy}>{copy}</Text></View></View>)}</ScrollView>; }
function Rows({ items }: { items: string[] }) { return <View style={styles.rows}>{items.map((item) => <View key={item} style={styles.row}><Text style={styles.rowText}>{item}</Text><Text style={styles.chevron}>›</Text></View>)}</View>; }
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: color.bg }, content: { padding: space.lg, paddingTop: 60, paddingBottom: 40 }, back: { color: color.muted, fontFamily: font.bodyMedium, marginBottom: 18 }, title: { color: color.text, fontFamily: font.display, fontSize: 34 }, copy: { color: color.muted, fontFamily: font.body, fontSize: type.body, lineHeight: 23, marginTop: 8 }, work: { flexDirection: 'row', alignItems: 'center', gap: 12, marginTop: 22, padding: 12, backgroundColor: color.surface, borderColor: color.border, borderWidth: 1, borderRadius: radius.md }, workTitle: { color: color.text, fontFamily: font.displayMedium, fontSize: type.subtitle }, meta: { color: color.muted, fontFamily: font.body, fontSize: type.caption, marginTop: 3 }, rows: { backgroundColor: color.surface, borderWidth: 1, borderColor: color.border, borderRadius: radius.md, overflow: 'hidden' }, row: { minHeight: 48, paddingHorizontal: 14, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: color.border }, rowText: { color: color.text, fontFamily: font.body, fontSize: type.caption }, chevron: { color: color.muted, fontSize: 22 }, note: { flexDirection: 'row', gap: 12, paddingVertical: 18, borderBottomWidth: StyleSheet.hairlineWidth, borderBottomColor: color.border }, noteMark: { color: color.accent, fontSize: 18 }, noteTitle: { color: color.text, fontFamily: font.displayMedium, fontSize: type.subtitle }, noteCopy: { color: color.muted, fontFamily: font.body, fontSize: type.caption, lineHeight: 18, marginTop: 4 } });
