import { useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { FlashList } from '@shopify/flash-list';
import { useCompare, type CompareCandidate, type FormatPrice } from './useCompare';
import { AppShell } from '../../ui/AppShell';
import { ComicRow } from '../../ui/comic';
import { Button, Eyebrow, Pill, Progress, PurchaseBadge, SectionHeader, Sheet } from '../../ui/primitives';
import { color, font, radius, space, type } from '../../ui/tokens';
const money = (paise: number) => `₹${Math.round(paise / 100).toLocaleString('en-IN')}`;
export default function CompareScreen() { const data = useCompare(); const [tab, setTab] = useState<'single' | 'multiple'>('single'); const [budget, setBudget] = useState(false); const [pick, setPick] = useState(false); const first = data.candidates[0]; const listData = tab === 'multiple' ? data.candidates : first ? [first] : []; const pickedFormatPrices = data.pick ? data.candidates.find((candidate) => candidate.id === data.pick!.id)?.formatPrices ?? [] : [];
 return <AppShell active="compare" title="Compare"><FlashList data={listData} keyExtractor={(item) => item.id} getItemType={() => tab === 'multiple' ? 'compare-row' : 'compare-single'} renderItem={({ item }) => tab === 'multiple' ? <ComicRow title={item.title} recyclingKey={item.id} meta={formatSummary(item.formatPrices)} label={item.label} /> : <SingleTitle item={item} />} contentContainerStyle={styles.content} ListHeaderComponent={<><View style={styles.tabs}><Pill label="Single title" active={tab === 'single'} onPress={() => setTab('single')} /><Pill label="Multiple titles" active={tab === 'multiple'} onPress={() => setTab('multiple')} /></View><View style={styles.budgetRow}><Text style={styles.budgetText}>Monthly budget · {money(data.budgetPaise)}</Text><Text onPress={() => setBudget(true)} style={styles.budgetAction}>Adjust</Text></View>{tab === 'multiple' ? <SectionHeader title="Your shortlist" /> : null}</>} ListFooterComponent={tab === 'multiple' ? <Button style={{ marginTop: 24 }} onPress={() => setPick(true)}>Pick one for me</Button> : null}/>{budget ? <View style={styles.overlay}><Sheet title="Monthly budget"><Text style={styles.sheetCopy}>Stay in control. ComicPill will never overfill your basket.</Text><View style={styles.presets}>{[50000, 100000, 200000, 300000, 500000].map((value) => <Pill key={value} label={money(value)} active={data.budgetPaise === value} onPress={() => data.setBudgetPaise(value)} />)}</View><Text style={styles.remaining}>{money(data.budgetPaise - data.basket.totalPaise)} remaining after your basket</Text><Progress value={data.budgetPaise ? data.basket.totalPaise / data.budgetPaise : 0} /><Button style={{ marginTop: 18 }} onPress={() => setBudget(false)}>Save budget</Button></Sheet></View> : null}{pick ? <View style={styles.overlay}><Sheet title="Pick one for me">{data.pick ? <><Eyebrow>ComicPill recommends</Eyebrow><Text numberOfLines={2} ellipsizeMode="tail" style={styles.pickTitle}>{data.pick.title}</Text><Text style={styles.pickPrice}>{formatSummary(pickedFormatPrices)}</Text><View style={styles.pickReasons}><Text>✦ Fits your current taste</Text><Text>✦ Makes sense inside your budget</Text><Text>✦ Adds real keeper value</Text></View><Button onPress={() => setPick(false)}>Add to basket</Button></> : <><Text style={styles.pickTitle}>Buy nothing right now.</Text><Text style={styles.sheetCopy}>Your budget is better saved for the next great fit.</Text><Button kind="secondary" onPress={() => setPick(false)}>Close</Button></>}</Sheet></View> : null}</AppShell>; }
function formatSummary(formatPrices: FormatPrice[]) { return formatPrices.map(({ format, pricePaise }) => `${format === 'digital' ? 'Digital' : 'Physical'} ${money(pricePaise)}`).join(' · '); }
function FormatCard({ edition }: { edition: FormatPrice }) { const isDigital = edition.format === 'digital'; return <View style={styles.format}><Text style={styles.formatLabel}>{isDigital ? 'Digital' : 'Physical'}</Text><Text style={styles.price}>{money(edition.pricePaise)}</Text><Text style={styles.formatCopy}>{isDigital ? 'Instant access\nLower price' : 'Shelf value\nArtwork & presence'}</Text><Button kind={isDigital ? 'secondary' : 'primary'}>{isDigital ? 'Buy digital' : 'Buy physical'}</Button></View>; }
function verdictCopy(label: ReturnType<typeof useCompare>['candidates'][number]['label']) { return { collect: 'Worth owning in print.', buy_on_sale: 'Worth considering at the right price.', digital_is_fine: 'Great digitally. Save the shelf space.', try_digital_first: 'Read it first. Then decide.', skip: 'Not a purchase priority right now.' }[label]; }
function SingleTitle({ item }: { item: CompareCandidate & { label: ReturnType<typeof useCompare>['candidates'][number]['label']; waitForPricePaise: number | null } }) { return <><Eyebrow>Compare formats</Eyebrow><Text numberOfLines={3} ellipsizeMode="tail" style={styles.heroTitle}>{item.title}</Text><View style={styles.formats}>{item.formatPrices.map((edition) => <FormatCard key={edition.format} edition={edition} />)}</View><View style={styles.verdict}><Eyebrow>ComicPill verdict</Eyebrow><PurchaseBadge label={item.label} /><Text style={styles.verdictTitle}>{verdictCopy(item.label)}</Text><Text style={styles.verdictCopy}>The best buy is the one that serves your reading life and your shelf.</Text>{item.waitForPricePaise != null ? <Text style={styles.waitFor}>Wait for a price at or below {money(item.waitForPricePaise)}</Text> : null}</View></>; }
const styles = StyleSheet.create({ content: { padding: space.lg, paddingBottom: 104 }, tabs: { flexDirection: 'row', gap: 8 }, budgetRow: { marginVertical: 18, padding: 12, backgroundColor: color.surface2, borderRadius: radius.md, flexDirection: 'row', justifyContent: 'space-between' }, budgetText: { color: color.muted, fontFamily: font.body, fontSize: type.caption }, budgetAction: { color: color.accent, fontFamily: font.bodySemibold, fontSize: type.caption }, heroTitle: { color: color.text, fontFamily: font.display, fontSize: 30, marginTop: 7, marginBottom: 18 }, formats: { flexDirection: 'row', gap: 10 }, format: { flex: 1, minHeight: 230, backgroundColor: color.surface, borderRadius: radius.lg, padding: 14, borderWidth: 1, borderColor: color.border, justifyContent: 'space-between' }, formatLabel: { color: color.muted, fontFamily: font.bodySemibold, fontSize: type.caption, textTransform: 'uppercase', letterSpacing: 1 }, price: { color: color.text, fontFamily: font.display, fontSize: 26, marginTop: 7 }, formatCopy: { color: color.muted, fontFamily: font.body, fontSize: 12, lineHeight: 18 }, verdict: { marginTop: 18, borderRadius: radius.lg, padding: 16, borderWidth: 1, borderColor: color.collectGold + '66', backgroundColor: color.surface }, verdictTitle: { color: color.text, fontFamily: font.display, fontSize: type.title, marginTop: 10 }, verdictCopy: { color: color.muted, fontFamily: font.body, fontSize: type.caption, lineHeight: 18, marginTop: 5 }, waitFor: { color: color.warning, fontFamily: font.bodySemibold, fontSize: type.caption, marginTop: 10 }, overlay: { ...StyleSheet.absoluteFill, zIndex: 5, justifyContent: 'flex-end', backgroundColor: '#000000aa' }, sheetCopy: { color: color.muted, fontFamily: font.body, fontSize: type.body, lineHeight: 22, marginBottom: 15 }, presets: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 18 }, remaining: { color: color.text, fontFamily: font.bodyMedium, fontSize: type.caption, marginBottom: 8 }, pickTitle: { color: color.text, fontFamily: font.display, fontSize: 27, marginTop: 8 }, pickPrice: { color: color.collectGold, fontFamily: font.bodySemibold, marginTop: 5 }, pickReasons: { gap: 10, marginVertical: 20 } });
