import { useEffect, useMemo, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { FlashList } from '@shopify/flash-list';
import { router, useLocalSearchParams } from 'expo-router';
import { useCompare, type CompareCandidate, type FormatPrice } from './useCompare';
import { useReadCompare, type SearchCandidate } from './useReadCompare';
import type { CompareChallenge, CompareResult } from '../../lib/engines/compare/verdict';
import { AppShell } from '../../ui/AppShell';
import { ComicRow } from '../../ui/comic';
import { Button, Eyebrow, Input, Pill, Progress, PurchaseBadge, SectionHeader, Sheet } from '../../ui/primitives';
import { color, font, radius, space, type } from '../../ui/tokens';

const money = (paise: number) => `₹${Math.round(paise / 100).toLocaleString('en-IN')}`;
const CATEGORY_LABEL: Record<CompareResult['category'], string> = { read_first: 'READ FIRST', read_next: 'READ NEXT', save_for_later: 'SAVE FOR LATER', skip_for_now: 'SKIP FOR NOW' };
const CATEGORY_RANK: Record<CompareResult['category'], number> = { read_first: 0, read_next: 1, save_for_later: 2, skip_for_now: 3 };
const DIMENSION_LABEL: Record<CompareResult['dimensions'][number]['key'], string> = { readiness: 'Readiness', tasteMatch: 'Taste Match', moodMatch: 'Mood Match', storyFit: 'Story Fit', artwork: 'Artwork', characterInterest: 'Character Interest', commitment: 'Reading Commitment', availability: 'Collection', pathRelevance: 'Path Relevance', variety: 'Variety' };

export default function CompareScreen() {
  const [mode, setMode] = useState<'read' | 'buy'>('read');
  return <AppShell active="compare" title="Compare"><View style={styles.modeTabs}><Pill label="Read" active={mode === 'read'} onPress={() => setMode('read')} /><Pill label="Buy" active={mode === 'buy'} onPress={() => setMode('buy')} /></View>{mode === 'read' ? <ReadCompare /> : <BuyCompare />}</AppShell>;
}

function ReadCompare() {
  const { workId, mood } = useLocalSearchParams<{ workId?: string; mood?: string }>();
  const read = useReadCompare(); const [showFull, setShowFull] = useState(false);
  const { addCandidate } = read;
  const prefilledId = Array.isArray(workId) ? workId[0] : workId;
  const selectedMood = Array.isArray(mood) ? mood[0] : mood ?? null;
  useEffect(() => { if (prefilledId) addCandidate(prefilledId); }, [prefilledId, addCandidate]);
  const ranked = useMemo(() => read.outcome ? [...read.outcome.results].sort((a, b) => CATEGORY_RANK[a.category] - CATEGORY_RANK[b.category] || b.overallScore - a.overallScore) : [], [read.outcome]);
  const titleFor = (id: string) => read.selected.find((item) => item?.workId === id)?.title ?? 'Comic';

  if (read.outcome) return <ReadResults ranked={ranked} titleFor={titleFor} challenge={read.outcome.challenge} showFull={showFull} setShowFull={setShowFull} onEdit={() => read.setSlot(0, read.slots[0])} />;
  return <FlashList data={read.slots} keyExtractor={(_, index) => `compare-slot-${index}`} getItemType={() => 'compare-slot'} contentContainerStyle={styles.content} renderItem={({ item, index }) => <CandidateSlot index={index} selectedId={item} selected={read.selected[index]} search={read.search} onSelect={(id) => read.setSlot(index, id)} onClear={() => read.setSlot(index, null)} />} ListHeaderComponent={<><Text style={styles.readIntro}>What should you read next?</Text><Text style={styles.readCopy}>Compare a few real options. ComicPill will give you a clear order, not a score.</Text></>} ListFooterComponent={<>{read.slots.length < 6 ? <Button kind="secondary" style={{ marginTop: 8 }} onPress={read.addSlot}>+ Compare another</Button> : null}<Button disabled={!read.canCompare} style={{ marginTop: 12 }} onPress={() => read.run(selectedMood)}>Compare</Button></>} />;
}

function CandidateSlot({ index, selectedId, selected, search, onSelect, onClear }: { index: number; selectedId: string | null; selected: ReturnType<typeof useReadCompare>['selected'][number]; search: (query: string) => SearchCandidate[]; onSelect: (workId: string) => void; onClear: () => void }) {
  const [query, setQuery] = useState(''); const results = query.trim() ? search(query) : [];
  const groups: [SearchCandidate['group'], string][] = [['library', 'My Library'], ['wishlist', 'Wishlist'], ['catalog', 'Catalog']];
  return <View style={styles.slot}><View style={styles.slotHeading}><Text style={styles.slotLabel}>Comic {String.fromCharCode(65 + index)}</Text>{selectedId ? <Pressable onPress={onClear}><Text style={styles.clearSlot}>Clear</Text></Pressable> : null}</View>{selected ? <View style={styles.selected}><Text numberOfLines={2} style={styles.selectedTitle}>{selected.title}</Text><Text style={styles.selectedMeta}>{ownershipLabel({ own: selected.own, status: selected.status })}</Text><Text style={styles.changeHint}>Search below to replace it</Text></View> : null}<Input placeholder={selected ? 'Replace this comic…' : 'Search title, creator, or character'} value={query} onChangeText={setQuery} />{results.length ? <View style={styles.searchResults}>{groups.map(([group, heading]) => { const matches = results.filter((result) => result.group === group); return matches.length ? <View key={group}><Text style={styles.searchGroup}>{heading}</Text>{matches.map((result) => <Pressable key={result.workId} onPress={() => { onSelect(result.workId); setQuery(''); }} style={styles.searchResult}><View style={styles.resultBody}><Text numberOfLines={1} style={styles.resultTitle}>{result.title}</Text><Text numberOfLines={1} style={styles.resultMeta}>{ownershipLabel(result)}{result.creators[0] ? ` · ${result.creators[0]}` : ''}</Text></View><Text style={styles.resultAdd}>+</Text></Pressable>)}</View> : null; })}</View> : query.trim() ? <Text style={styles.noResults}>No comics match that search.</Text> : null}</View>;
}

function ownershipLabel(candidate: Pick<SearchCandidate, 'own' | 'status'>) {
  const own = candidate.own === 'physical' ? 'Physical' : candidate.own === 'digital' ? 'Digital' : candidate.own === 'both' ? 'Physical & digital' : candidate.own === 'subscription' ? 'Subscription' : candidate.own === 'wishlist' ? 'Wishlist' : candidate.own === 'ordered' ? 'Ordered' : 'Not owned';
  const status = candidate.status === 'none' ? 'Unread' : candidate.status === 'done' ? 'Finished' : candidate.status;
  return `${own} · ${status}`;
}

function ReadResults({ ranked, titleFor, challenge, showFull, setShowFull, onEdit }: { ranked: CompareResult[]; titleFor: (workId: string) => string; challenge: CompareChallenge | null; showFull: boolean; setShowFull: (next: boolean) => void; onEdit: () => void }) {
  const winner = ranked[0];
  return <FlashList data={ranked} keyExtractor={(item) => item.workId} getItemType={() => 'read-result'} contentContainerStyle={styles.content} renderItem={({ item, index }) => <Pressable onPress={() => router.push(`/comic/${item.workId}`)} style={styles.resultRow}><Text style={styles.rank}>{index + 1}</Text><View style={styles.resultBody}><Text numberOfLines={2} style={styles.resultTitle}>{titleFor(item.workId)}</Text><Text style={[styles.category, item.category === 'read_first' && styles.categoryFirst]}>{CATEGORY_LABEL[item.category]}</Text></View><Text style={styles.resultChevron}>›</Text></Pressable>} ListHeaderComponent={<>{challenge ? <View style={styles.challenge}><Eyebrow>ComicPill challenge</Eyebrow><Text style={styles.challengeCopy}>{challenge.message}</Text>{challenge.betterAlternativeWorkId ? <Button kind="secondary" style={{ marginTop: 12 }} onPress={() => router.push(`/comic/${challenge.betterAlternativeWorkId}`)}>View the better option</Button> : null}</View> : null}<Text style={styles.resultsHeading}>Your reading order</Text>{winner ? <View style={styles.winner}><Eyebrow>Why read this first?</Eyebrow><Text style={styles.winnerTitle}>{titleFor(winner.workId)}</Text>{winner.reasons.map((reason) => <Text key={reason} style={styles.reason}>• {reason}</Text>)}</View> : null}<SectionHeader title="Ranked choices" /></>} ListFooterComponent={<><Pressable onPress={() => setShowFull(!showFull)} style={styles.fullToggle}><Text style={styles.fullToggleText}>{showFull ? 'Hide full comparison' : 'See full comparison'}</Text></Pressable>{showFull ? <DimensionTable results={ranked} titleFor={titleFor} /> : null}<Button kind="secondary" style={{ marginTop: 18 }} onPress={onEdit}>Edit choices</Button></>} />;
}

function DimensionTable({ results, titleFor }: { results: CompareResult[]; titleFor: (workId: string) => string }) {
  return <View style={styles.table}>{results[0]?.dimensions.map((dimension) => <View key={dimension.key} style={styles.dimension}><Text style={styles.dimensionName}>{DIMENSION_LABEL[dimension.key]}</Text>{results.map((result) => <View key={result.workId} style={styles.dimensionValue}><Text numberOfLines={1} style={styles.dimensionComic}>{titleFor(result.workId)}</Text><Text style={styles.dimensionLabel}>{result.dimensions.find((item) => item.key === dimension.key)?.label}</Text></View>)}</View>)}</View>;
}

function BuyCompare() { const data = useCompare(); const [tab, setTab] = useState<'single' | 'multiple'>('single'); const [budget, setBudget] = useState(false); const [pick, setPick] = useState(false); const first = data.candidates[0]; const listData = tab === 'multiple' ? data.candidates : first ? [first] : []; const pickedFormatPrices = data.pick ? data.candidates.find((candidate) => candidate.id === data.pick!.id)?.formatPrices ?? [] : [];
 return <><FlashList data={listData} keyExtractor={(item) => item.id} getItemType={() => tab === 'multiple' ? 'compare-row' : 'compare-single'} renderItem={({ item }) => tab === 'multiple' ? <ComicRow title={item.title} recyclingKey={item.id} meta={formatSummary(item.formatPrices)} label={item.label} /> : <SingleTitle item={item} />} contentContainerStyle={styles.content} ListHeaderComponent={<><View style={styles.tabs}><Pill label="Single title" active={tab === 'single'} onPress={() => setTab('single')} /><Pill label="Multiple titles" active={tab === 'multiple'} onPress={() => setTab('multiple')} /></View><View style={styles.budgetRow}><Text style={styles.budgetText}>Monthly budget · {money(data.budgetPaise)}</Text><Text onPress={() => setBudget(true)} style={styles.budgetAction}>Adjust</Text></View>{tab === 'multiple' ? <SectionHeader title="Your shortlist" /> : null}</>} ListFooterComponent={tab === 'multiple' ? <Button style={{ marginTop: 24 }} onPress={() => setPick(true)}>Pick one for me</Button> : null}/>{budget ? <View style={styles.overlay}><Sheet title="Monthly budget"><Text style={styles.sheetCopy}>Stay in control. ComicPill will never overfill your basket.</Text><View style={styles.presets}>{[50000, 100000, 200000, 300000, 500000].map((value) => <Pill key={value} label={money(value)} active={data.budgetPaise === value} onPress={() => data.setBudgetPaise(value)} />)}</View><Text style={styles.remaining}>{money(data.budgetPaise - data.basket.totalPaise)} remaining after your basket</Text><Progress value={data.budgetPaise ? data.basket.totalPaise / data.budgetPaise : 0} /><Button style={{ marginTop: 18 }} onPress={() => setBudget(false)}>Save budget</Button></Sheet></View> : null}{pick ? <View style={styles.overlay}><Sheet title="Pick one for me">{data.pick ? <><Eyebrow>ComicPill recommends</Eyebrow><Text numberOfLines={2} ellipsizeMode="tail" style={styles.pickTitle}>{data.pick.title}</Text><Text style={styles.pickPrice}>{formatSummary(pickedFormatPrices)}</Text><View style={styles.pickReasons}><Text>✦ Fits your current taste</Text><Text>✦ Makes sense inside your budget</Text><Text>✦ Adds real keeper value</Text></View><Button onPress={() => setPick(false)}>Add to basket</Button></> : <><Text style={styles.pickTitle}>Buy nothing right now.</Text><Text style={styles.sheetCopy}>Your budget is better saved for the next great fit.</Text><Button kind="secondary" onPress={() => setPick(false)}>Close</Button></>}</Sheet></View> : null}</>; }
function formatSummary(formatPrices: FormatPrice[]) { return formatPrices.map(({ format, pricePaise }) => `${format === 'digital' ? 'Digital' : 'Physical'} ${money(pricePaise)}`).join(' · '); }
function FormatCard({ edition }: { edition: FormatPrice }) { const isDigital = edition.format === 'digital'; return <View style={styles.format}><Text style={styles.formatLabel}>{isDigital ? 'Digital' : 'Physical'}</Text><Text style={styles.price}>{money(edition.pricePaise)}</Text><Text style={styles.formatCopy}>{isDigital ? 'Instant access\nLower price' : 'Shelf value\nArtwork & presence'}</Text><Button kind={isDigital ? 'secondary' : 'primary'}>{isDigital ? 'Buy digital' : 'Buy physical'}</Button></View>; }
function verdictCopy(label: ReturnType<typeof useCompare>['candidates'][number]['label']) { return { collect: 'Worth owning in print.', buy_on_sale: 'Worth considering at the right price.', digital_is_fine: 'Great digitally. Save the shelf space.', try_digital_first: 'Read it first. Then decide.', skip: 'Not a purchase priority right now.' }[label]; }
function SingleTitle({ item }: { item: CompareCandidate & { label: ReturnType<typeof useCompare>['candidates'][number]['label']; waitForPricePaise: number | null } }) { return <><Eyebrow>Compare formats</Eyebrow><Text numberOfLines={3} ellipsizeMode="tail" style={styles.heroTitle}>{item.title}</Text><View style={styles.formats}>{item.formatPrices.map((edition) => <FormatCard key={edition.format} edition={edition} />)}</View><View style={styles.verdict}><Eyebrow>ComicPill verdict</Eyebrow><PurchaseBadge label={item.label} /><Text style={styles.verdictTitle}>{verdictCopy(item.label)}</Text><Text style={styles.verdictCopy}>The best buy is the one that serves your reading life and your shelf.</Text>{item.waitForPricePaise != null ? <Text style={styles.waitFor}>Wait for a price at or below {money(item.waitForPricePaise)}</Text> : null}</View></>; }

const styles = StyleSheet.create({
  modeTabs: { flexDirection: 'row', gap: 8, paddingHorizontal: space.lg, paddingTop: 4 }, content: { padding: space.lg, paddingBottom: 104 }, readIntro: { color: color.text, fontFamily: font.display, fontSize: 29, marginTop: 18 }, readCopy: { color: color.muted, fontFamily: font.body, fontSize: type.body, lineHeight: 22, marginTop: 7, marginBottom: 18 },
  slot: { backgroundColor: color.surface, borderColor: color.border, borderWidth: 1, borderRadius: radius.md, padding: space.md, marginBottom: 12 }, slotHeading: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 }, slotLabel: { color: color.text, fontFamily: font.bodySemibold, fontSize: type.caption, textTransform: 'uppercase', letterSpacing: 1 }, clearSlot: { color: color.accent, fontFamily: font.bodySemibold, fontSize: type.caption }, selected: { borderLeftColor: color.accent, borderLeftWidth: 3, paddingLeft: 10, marginBottom: 12 }, selectedTitle: { color: color.text, fontFamily: font.displayMedium, fontSize: type.subtitle }, selectedMeta: { color: color.muted, fontFamily: font.body, fontSize: type.caption, marginTop: 3 }, changeHint: { color: color.faint, fontFamily: font.body, fontSize: 11, marginTop: 5 },
  searchResults: { marginTop: 10 }, searchGroup: { color: color.faint, fontFamily: font.bodySemibold, fontSize: 10, letterSpacing: 1, textTransform: 'uppercase', marginTop: 10, marginBottom: 3 }, searchResult: { minHeight: 48, flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderBottomColor: color.border, borderBottomWidth: StyleSheet.hairlineWidth }, resultBody: { flex: 1, minWidth: 0 }, resultTitle: { color: color.text, fontFamily: font.bodySemibold, fontSize: type.body }, resultMeta: { color: color.muted, fontFamily: font.body, fontSize: 11, marginTop: 2 }, resultAdd: { color: color.accent, fontSize: 24, marginLeft: 10 }, noResults: { color: color.muted, fontFamily: font.body, fontSize: type.caption, marginTop: 10 },
  challenge: { marginTop: 16, padding: space.md, borderRadius: radius.md, borderColor: color.warning + '88', borderWidth: 1, backgroundColor: color.surface2 }, challengeCopy: { color: color.text, fontFamily: font.displayMedium, fontSize: type.subtitle, lineHeight: 23, marginTop: 6 }, resultsHeading: { color: color.text, fontFamily: font.display, fontSize: 29, marginTop: 18 }, winner: { marginTop: 14, padding: space.md, backgroundColor: color.surface, borderColor: color.accent + '88', borderWidth: 1, borderRadius: radius.md }, winnerTitle: { color: color.text, fontFamily: font.display, fontSize: type.title, marginTop: 5, marginBottom: 8 }, reason: { color: color.muted, fontFamily: font.body, fontSize: type.caption, lineHeight: 20, marginTop: 3 }, resultRow: { minHeight: 72, flexDirection: 'row', alignItems: 'center', gap: 12, borderBottomColor: color.border, borderBottomWidth: StyleSheet.hairlineWidth }, rank: { color: color.accent, fontFamily: font.display, fontSize: 25, width: 24, textAlign: 'center' }, category: { color: color.muted, fontFamily: font.bodySemibold, fontSize: 10, letterSpacing: 1, marginTop: 4 }, categoryFirst: { color: color.accent }, resultChevron: { color: color.muted, fontSize: 24 }, fullToggle: { alignItems: 'center', paddingVertical: 15, marginTop: 8 }, fullToggleText: { color: color.accent, fontFamily: font.bodySemibold, fontSize: type.caption }, table: { borderColor: color.border, borderWidth: 1, borderRadius: radius.md, overflow: 'hidden' }, dimension: { padding: 10, borderBottomColor: color.border, borderBottomWidth: StyleSheet.hairlineWidth }, dimensionName: { color: color.text, fontFamily: font.bodySemibold, fontSize: type.caption, marginBottom: 5 }, dimensionValue: { flexDirection: 'row', justifyContent: 'space-between', gap: 10, paddingVertical: 2 }, dimensionComic: { color: color.muted, fontFamily: font.body, fontSize: 11, flex: 1 }, dimensionLabel: { color: color.text, fontFamily: font.bodyMedium, fontSize: 11 },
  tabs: { flexDirection: 'row', gap: 8 }, budgetRow: { marginVertical: 18, padding: 12, backgroundColor: color.surface2, borderRadius: radius.md, flexDirection: 'row', justifyContent: 'space-between' }, budgetText: { color: color.muted, fontFamily: font.body, fontSize: type.caption }, budgetAction: { color: color.accent, fontFamily: font.bodySemibold, fontSize: type.caption }, heroTitle: { color: color.text, fontFamily: font.display, fontSize: 30, marginTop: 7, marginBottom: 18 }, formats: { flexDirection: 'row', gap: 10 }, format: { flex: 1, minHeight: 230, backgroundColor: color.surface, borderRadius: radius.lg, padding: 14, borderWidth: 1, borderColor: color.border, justifyContent: 'space-between' }, formatLabel: { color: color.muted, fontFamily: font.bodySemibold, fontSize: type.caption, textTransform: 'uppercase', letterSpacing: 1 }, price: { color: color.text, fontFamily: font.display, fontSize: 26, marginTop: 7 }, formatCopy: { color: color.muted, fontFamily: font.body, fontSize: 12, lineHeight: 18 }, verdict: { marginTop: 18, borderRadius: radius.lg, padding: 16, borderWidth: 1, borderColor: color.collectGold + '66', backgroundColor: color.surface }, verdictTitle: { color: color.text, fontFamily: font.display, fontSize: type.title, marginTop: 10 }, verdictCopy: { color: color.muted, fontFamily: font.body, fontSize: type.caption, lineHeight: 18, marginTop: 5 }, waitFor: { color: color.warning, fontFamily: font.bodySemibold, fontSize: type.caption, marginTop: 10 }, overlay: { ...StyleSheet.absoluteFill, zIndex: 5, justifyContent: 'flex-end', backgroundColor: '#000000aa' }, sheetCopy: { color: color.muted, fontFamily: font.body, fontSize: type.body, lineHeight: 22, marginBottom: 15 }, presets: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 18 }, remaining: { color: color.text, fontFamily: font.bodyMedium, fontSize: type.caption, marginBottom: 8 }, pickTitle: { color: color.text, fontFamily: font.display, fontSize: 27, marginTop: 8 }, pickPrice: { color: color.collectGold, fontFamily: font.bodySemibold, marginTop: 5 }, pickReasons: { gap: 10, marginVertical: 20 },
});
