#!/usr/bin/env python3
"""Retry pass for scripts/fetch-covers.py — only fetches covers still missing
after the first run, with retries and more conservative pacing (the first
pass hit connection resets/timeouts from Open Library partway through a
65-title burst, not genuine no-matches for most of them)."""
import json
import time
import urllib.request
import urllib.parse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CATALOG_PATH = ROOT / "src/lib/db/seed/catalog.data.json"
COVERS_DIR = ROOT / "assets/covers"
ASSET_MAP_PATH = ROOT / "src/ui/coverAssets.ts"
SOURCES_PATH = ROOT / "docs/cover-sources.json"

USER_AGENT = "ComicPill/1.0 (personal reading app; contact: mukund.umashankar@gmail.com)"
HEADERS = {"User-Agent": USER_AGENT}


def search_title(raw_title: str) -> str:
    t = re.sub(r"\s*\(.*?\)\s*", " ", raw_title)
    return re.sub(r"\s+", " ", t).strip()


def with_retry(fn, attempts=3, base_delay=2.0):
    last_err = None
    for i in range(attempts):
        try:
            return fn()
        except Exception as e:
            last_err = e
            time.sleep(base_delay * (i + 1))
    raise last_err


def open_library_search(title: str):
    q = urllib.parse.urlencode({"title": title, "limit": 3})
    url = f"https://openlibrary.org/search.json?{q}"
    def do():
        req = urllib.request.Request(url, headers=HEADERS)
        with urllib.request.urlopen(req, timeout=20) as resp:
            return json.load(resp)
    data = with_retry(do)
    for doc in data.get("docs", []):
        if doc.get("cover_i"):
            return doc
    return None


def fetch_cover_bytes(cover_i: int, size: str = "L"):
    url = f"https://covers.openlibrary.org/b/id/{cover_i}-{size}.jpg?default=false"
    def do():
        req = urllib.request.Request(url, headers=HEADERS)
        with urllib.request.urlopen(req, timeout=20) as resp:
            if resp.status != 200:
                return None
            return resp.read()
    return with_retry(do)


def main():
    rows = json.load(open(CATALOG_PATH))
    sources = json.loads(SOURCES_PATH.read_text()) if SOURCES_PATH.exists() else {}
    already = {p.stem for p in COVERS_DIR.glob("*.jpg")}
    missing_rows = [r for r in rows if r["id"] not in already]
    print(f"Retrying {len(missing_rows)} missing covers (already have {len(already)})")

    found = 0
    still_missing = []
    for i, row in enumerate(missing_rows):
        work_id, title = row["id"], row["title"]
        query = search_title(title)
        print(f"[{i+1}/{len(missing_rows)}] {title!r} -> {query!r}")
        try:
            doc = open_library_search(query)
        except Exception as e:
            print(f"    search failed after retries: {e}")
            still_missing.append(title)
            time.sleep(1.5)
            continue

        if not doc:
            print("    no cover found")
            still_missing.append(title)
            time.sleep(1.5)
            continue

        try:
            img_bytes = fetch_cover_bytes(doc["cover_i"])
        except Exception as e:
            print(f"    cover fetch failed after retries: {e}")
            still_missing.append(title)
            time.sleep(1.5)
            continue

        if not img_bytes or len(img_bytes) < 500:
            print("    placeholder-sized, skipping")
            still_missing.append(title)
            time.sleep(1.5)
            continue

        (COVERS_DIR / f"{work_id}.jpg").write_bytes(img_bytes)
        found += 1
        print(f"    saved ({len(img_bytes)} bytes)")
        sources[work_id] = {
            "title": title, "matchedTitle": doc.get("title"),
            "openLibraryWorkKey": doc.get("key"), "coverId": doc.get("cover_i"),
            "coverUrl": f"https://covers.openlibrary.org/b/id/{doc['cover_i']}-L.jpg",
            "source": "Open Library",
        }
        time.sleep(1.0)

    SOURCES_PATH.write_text(json.dumps(sources, indent=2))

    # Regenerate the asset map from whatever's actually on disk now.
    all_covers = sorted(p.stem for p in COVERS_DIR.glob("*.jpg"))
    requires = [f"  '{wid}': require('../../assets/covers/{wid}.jpg')," for wid in all_covers]
    asset_map_ts = (
        "// GENERATED by scripts/fetch-covers.py + fetch-covers-retry.py — do not hand-edit.\n"
        "// Metro requires static, bundle-time-known require() paths, so this map\n"
        "// (rather than a runtime-constructed path) is how a workId resolves to a\n"
        "// bundled cover asset. Re-run the scripts after catalog changes.\n"
        "import type { ImageSourcePropType } from 'react-native';\n\n"
        "export const COVER_ASSETS: Record<string, ImageSourcePropType> = {\n"
        + "\n".join(requires) + "\n"
        "};\n"
    )
    ASSET_MAP_PATH.write_text(asset_map_ts)

    total = len(all_covers)
    print(f"\nRetry done: +{found} recovered. Total now: {total}/{len(rows)}")
    if still_missing:
        print(f"Still missing {len(still_missing)}: {still_missing}")


if __name__ == "__main__":
    main()
