#!/usr/bin/env python3
"""
One-time script: fetch official cover thumbnails for the seed catalog from
Open Library's public covers API (the sanctioned, third-party-display use
case for that API — the same mechanism Goodreads/Libby/etc. use), and bundle
them as local app assets so covers load instantly with zero runtime network
dependency (see docs/PERFORMANCE.md).

Not run automatically — run by hand when the catalog changes:
    python3 scripts/fetch-covers.py

Writes:
  - assets/covers/<workId>.jpg           the bundled cover image
  - src/ui/coverAssets.ts                a static require() map (Metro needs
                                          static, bundle-time-known require()
                                          paths — this file is generated, not
                                          hand-written)
  - docs/cover-sources.json              attribution record per cover, for
                                          the Sources & Transparency screen
                                          (title matched, edition/work id on
                                          Open Library, the URL fetched)
"""
import json
import time
import urllib.request
import urllib.parse
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CATALOG_PATH = ROOT / "src/lib/db/seed/catalog.data.json"
COVERS_DIR = ROOT / "assets/covers"
ASSET_MAP_PATH = ROOT / "src/ui/coverAssets.ts"
SOURCES_PATH = ROOT / "docs/cover-sources.json"

USER_AGENT = "ComicPill/1.0 (personal reading app; contact: mukund.umashankar@gmail.com)"
HEADERS = {"User-Agent": USER_AGENT}

# Titles vary a lot from what Open Library indexes cleanly (subtitles, "Vol."
# suffixes, publisher-specific naming). A light cleanup improves match rate
# without inventing anything — same normalizeTitle spirit as the app's own
# title-matching ladder.
def search_title(raw_title: str) -> str:
    t = raw_title
    t = re.sub(r"\s*\(.*?\)\s*", " ", t)  # drop parenthetical years/notes
    t = re.sub(r"\s+", " ", t).strip()
    return t


def open_library_search(title: str):
    q = urllib.parse.urlencode({"title": title, "limit": 3})
    url = f"https://openlibrary.org/search.json?{q}"
    req = urllib.request.Request(url, headers=HEADERS)
    with urllib.request.urlopen(req, timeout=15) as resp:
        data = json.load(resp)
    for doc in data.get("docs", []):
        if doc.get("cover_i"):
            return doc
    return None


def fetch_cover_bytes(cover_i: int, size: str = "L") -> bytes | None:
    url = f"https://covers.openlibrary.org/b/id/{cover_i}-{size}.jpg?default=false"
    req = urllib.request.Request(url, headers=HEADERS)
    try:
        with urllib.request.urlopen(req, timeout=15) as resp:
            if resp.status != 200:
                return None
            return resp.read()
    except Exception:
        return None


def main():
    rows = json.load(open(CATALOG_PATH))
    COVERS_DIR.mkdir(parents=True, exist_ok=True)

    requires: list[str] = []
    sources: dict[str, dict] = {}
    found, missing = 0, []

    for i, row in enumerate(rows):
        work_id = row["id"]
        title = row["title"]
        query = search_title(title)
        print(f"[{i+1}/{len(rows)}] {title!r} -> searching {query!r}")

        doc = None
        try:
            doc = open_library_search(query)
        except Exception as e:
            print(f"    search failed: {e}")

        if not doc:
            missing.append(title)
            print("    no cover found")
            time.sleep(0.4)
            continue

        img_bytes = fetch_cover_bytes(doc["cover_i"])
        if not img_bytes or len(img_bytes) < 500:  # guard against 1x1 placeholder
            missing.append(title)
            print("    cover fetch failed or placeholder-sized")
            time.sleep(0.4)
            continue

        out_path = COVERS_DIR / f"{work_id}.jpg"
        out_path.write_bytes(img_bytes)
        found += 1
        print(f"    saved {out_path.relative_to(ROOT)} ({len(img_bytes)} bytes)")

        requires.append(f"  '{work_id}': require('../../assets/covers/{work_id}.jpg'),")
        sources[work_id] = {
            "title": title,
            "matchedTitle": doc.get("title"),
            "openLibraryWorkKey": doc.get("key"),
            "coverId": doc.get("cover_i"),
            "coverUrl": f"https://covers.openlibrary.org/b/id/{doc['cover_i']}-L.jpg",
            "source": "Open Library",
        }

        # Stay well under Open Library's stated rate limits (they ask for
        # 1 req/s unidentified, 3 req/s with a proper User-Agent) — this is a
        # one-time batch script, not a per-user runtime call.
        time.sleep(0.4)

    asset_map_ts = (
        "// GENERATED by scripts/fetch-covers.py — do not hand-edit.\n"
        "// Metro requires static, bundle-time-known require() paths, so this map\n"
        "// (rather than a runtime-constructed path) is how a workId resolves to a\n"
        "// bundled cover asset. Re-run the script after catalog changes.\n"
        "import type { ImageSourcePropType } from 'react-native';\n\n"
        "export const COVER_ASSETS: Record<string, ImageSourcePropType> = {\n"
        + "\n".join(requires) + "\n"
        "};\n"
    )
    ASSET_MAP_PATH.write_text(asset_map_ts)
    SOURCES_PATH.write_text(json.dumps(sources, indent=2))

    print(f"\nDone: {found}/{len(rows)} covers fetched.")
    if missing:
        print(f"No cover found for {len(missing)}: {missing}")


if __name__ == "__main__":
    main()
